import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Student {
  name: string;
  arabic: string;
  english: string;
  math: string;
  interdisciplinary: string;
  physical_education: string;
  religion: string;
  values: string;
  tokkatsu: string;
  result: string;
}

@Component({
  selector: 'app-second-grade',
  imports: [NgIf, FormsModule],
  templateUrl: './second-grade.component.html',
  styleUrl: './second-grade.component.css',
})
export class SecondGradeComponent {
  students: Student[] = [
    {
      name: 'ابراهيم احمد ابراهيم السيد محمد سمك',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ابراهيم عماد رشاد ابوالمعاطي الموجى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ابراهيم محمد كمال حامد علي',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد ابراهيم عادل احمد مصطفى',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد احمد نعمان احمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد معوض ابراهيم جمعه',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم اسلام هيثم منصور محمد زيادة',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم السيد عزمي عبد الفتاح',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر احمد صبري عيد سيد أحمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر محمد السيد العجمي المرسى',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر محمد عماد محمد محمد عبد ندا',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسرحماده يسري عبده الهجرسي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'السيد محمد بدير سليمان أبو المعاطى',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'انس احمد محمود محمد السيد',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'اياد رضافتحي الحنفي صلاح',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايساف محمد صبري محمد محمد علي',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'براء علي محمد علي محمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بشار هاني سمير سميراحمد عبد السلام',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسني يوسف محمد احمد ضيف الله',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حمزه محمد شعبان السعيد على',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خالد اسامة ابراهيم عبد السلام أحمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خالد وليد احمد محمد محمود المحجوب ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'راكان محمد خاطر مختار محمد سرايا',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان حماده حمدي نافع السيد غنيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان محمود علي محمد علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان محمود محمد ابراهيم محمد شهاب الدين',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد محمد عوض سيف الدين أحمد درويش',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زين ايمن عبد الغني أحمد على الوصيف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سليم محمود السيد رشاد شمس  الدين',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سند حامد احمد حامد ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف محمد السعيد عبد الجليل محمد زهران',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف محمود عبدالوهاب هاشم ابراهيم',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'طلال محمد عبد الفتاح محمد إبراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عاطف رفعت عطيه عبدالعزيز إبراهيم ',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن محمد عبد الرحمن جمعه ',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله محمود عبد الله محمد العفيفي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبدالله رضا السيد عبد العال صابر',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبدالله محمد محمد علي عبد الرؤف اسماعيل',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'علاء علاء منصور محمد سليمان المراكبى',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عماد احمد حمدي رافت رشاد',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر ابراهيم عبدالغني محمد رشدي عبد الغنى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر شريف اشرف ابراهيم عابدين بدوى ',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر شريف حسن سعد الحسينى',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر عوض محمد عوض محمد عبد الرحيم',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر مجدي شعبان السعيد علي الرفاعى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر محمد أنورمحمد عبد الواحد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر محمد عثمان مسعد ابراهيم الكنانى',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمرو خالد محمد سمير السيد ابراهيم',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فهمي محمود فهمي منصور محمد',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كريم محمد السيد المتولي عبد المعطى',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك عمرو احمد محمد السعيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد احمد احمد محمد علي إبراهيم',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السيد السيد علي المعلواني',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السيد المتولي علي الشافعي',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد تامر عوض محمد عيسى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد حازم عزمي عوضين محمد ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد رضا محمد محمد المرغني',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد سعد السيد السعيد العشري',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'محمد عبد الله عزمي عوضين محمد إبراهيم',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد علي ابراهيم المغازي ابراهيم',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد عمرو محمد ابراهيم عباس',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد كريم عنتر السيد محمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد مأمون مأمون محمود محمد الباز',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد ممدوح احمد السيد فرج',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود احمد محمد علي عبدالرؤوف اسماعيل',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود محمد احمد محمد الديب',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان عاطف عبد الوهاب عبد الفتاح',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان محمد علي علي فرج',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'معاذ محمد عبد الحافظ عبد الحافظ  محمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'منذر توفيق علي توفيق علي السيد الذكراوى ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مؤمن الحسين السيد محمد الدمرداش ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور محمد محمدابراهيم محمد عبد الرحيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين علي محمد علي محمد علي',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'ياسين محمد سعد عبد الله محمود',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يسن مجدي محمد عبد الرحمن عبد الغنى',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يسن محمد أحمد السيد الغريب',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'يوسف احمد السيد محمد مصطفى',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف احمد حمزه علي ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف احمد محمد أحمد سليمان ',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف بسام ممدوح محمودعبدالرؤوف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسيل السعيد العدل العدل محمد الجزار ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسيل حسين إبراهيم إبراهيم السيد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايسل السيد عادل عبد المنعم محمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايملي عوض محمد عوض محمد ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايه احمد عثمان ابراهيم الوصيف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تالا وليد احمد احمد ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ثناء محمود علي السيد محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جاسمن محمد السعيد السيد علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي عادل حسين سيد احمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي عماد رزق محمد حسن ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جوري هيثم السعيد على محمد ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حبيبة عبد الحي الشحات عبد احمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ديما اسلام حسن عبده المرسي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ديمه عاطف محمد على السيد الزلاط',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رانيا محمد محمود الشبراوي عبد الرحمن',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رانيا محمد مختار منصور محمد إبراهيم',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رحمه ماهر عبدالوهاب احمد محمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رغد عادل ابراهيم محمد السيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رغد محمد جمعه احمد ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رهف محمد جمعه احمد ابراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رودينا حميدو عثمان ابراهيم الوصيف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'روضة الدمرداش محمد جمعة العجمى',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'روضة محمد صالح عبد الحميد السيد ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتاج محمد رشد ي محمد فرج',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زينا السيد صبري منصور السعيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساجده احمد ابراهيم عبدالمجيد محمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سارة سيف احمد الششتاوي علي',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي مجدي ابراهيم محمد السيد',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سدره احمد محمد عبد الحميد محمد بلال',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سدره علاء الدمرداش جمعة العجمي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سدره محمد عبد المنعم أحمد العدوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سدره محمد محمد محمود المتولي النجار',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سلمى محمد سيد طاهر على',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما محمد احمد علي محمد الشنيطى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلفا حسين ابو الحسن على البيومى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عالية نصر عماد الدين عبد العزيز نصر الدين',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عائشة صالح احمد ابراهيم محمد ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عائشه احمد محمد طه ابراهيم الشنيطى ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فادية محمد السعيد عبد الهادي السيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كارما الساداتي محمد البسيوني عبده سلطان',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كايلا وائل سمير رمضان أمين',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لانا ايمن رضا ايمن محمود محمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لليان محمد محمد عبد الهادي أحمد الأمين',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لوجي احمد سمير محمد محمد خيوه',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'لوجين علي محمد علي محمد علي',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'لين  اكرم خاطرمختار محمد سرايا',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لينا السيد محمد عبد الفتاح إبراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لينا محمد حمدي عبد الحميد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليندا إسلام عبد القادر عبد السلام محمد',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'ماسة علاء بدوي عبد الرحمن بدوي',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ماسة على حسن رشاد حسن',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مايا علي علي علي ابو الليف',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروة اشرف ابراهيم عبد السلام',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم حسام فارووق محمد محمدابو العطا',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم علاء محمود ابو هاشم معروف',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم يوسف محمد عبد الدايم محسن',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكة السيد عبد الغني احمد علي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكه علي نافع محمود نافع نافع',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكه يحيى عبدالله محمد العفيفي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك اشرف ابراهيم ابراهيم أحمد ',
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميرنا وليد جمعه محمد علي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نادية حمادة محمد ابراهيم عباس',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ندى عصام المرسي ابراهيم هدهد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور ايمن عبد الوهاب محمد عبد الوهاب',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور محمد حسين الدمرداش فرج',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور محمود عبدالله عبدالله محمود',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورا ابراهيم عبد الرؤوف عبده أبو المعاطى',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورين عماد  الدين عبد  البديع محمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نيفال محمد محمد الحبشي علي سيد أحمد',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'هاجر عثمان ابوحلاوه عثمان علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا احمد محسن احمد ابو الحسن',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا محمد  احمد نور الدين المتولى',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هيام السيد محمد عبده الطنطاوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
  ];

  studentName: string = '';
  selectedStudent: Student | null = null;

  searchStudent() {
    const input = this.studentName.trim();
    const words = input.split(' ');

    if (words.length < 3) {
      this.selectedStudent = null;
      alert('أدخل اسم الطالب ثلاثي');
      return;
    }

    const firstThreeWords = words.slice(0, 3).join(' ');

    this.selectedStudent =
      this.students.find((s) => s.name.startsWith(firstThreeWords)) || null;
  }
}
