import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Student {
  name: string;
  seatnumber: number;
  arabic: string;
  math: string;
  studies: string;
  sciences: string;
  english: string;
  ict: string;
  profess_Skills: string;
  total: string;
  religion: string;
  art: string;
  physicalEducation: string;
  musicEducation: string;
  tokkatsu: string;
  result: string;
}

@Component({
  selector: 'app-fifth-grade',
  imports: [NgIf, FormsModule],
  templateUrl: './fifth-grade.component.html',
  styleUrl: './fifth-grade.component.css',
})
export class FifthGradeComponent {
  students: Student[] = [
    {
      name: 'ابراهيم خالد إبراهيم محمد رمضان',
      seatnumber: 30,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ابراهيم محمد ابراهيم محمد العراقي',
      seatnumber: 31,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'احمد ابراهيم السيد علي محمد',
      seatnumber: 32,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'احمد أشرف أحمد عبد الشافي حسن',
      seatnumber: 33,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'احمد جميل أحمد عبد الفتاح ابراهيم',
      seatnumber: 34,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'احمد محمود أحمد جاد أحمد ',
      seatnumber: 35,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'احمد مصطفى ماهر عبده محمد مصطفى',
      seatnumber: 36,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم ابراهيم محمد ابراهيم عيد طه',
      seatnumber: 37,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم أحمد السعيدمحمد شهده',
      seatnumber: 38,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم أشرف السيد أحمد ابراهيم  النجار',
      seatnumber: 39,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم رائد فهمي حسن يونس',
      seatnumber: 40,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم محمد المتولي عبدالعزيز',
      seatnumber: 41,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ادم محمد محمد ابراهيم عبد الرحيم',
      seatnumber: 42,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اسر محمد السعيد عبد الهادي',
      seatnumber: 43,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'الدسوقي محمد معوض ابراهيم جمعه',
      seatnumber: 44,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'السيد علي أكرم علي محمدين',
      seatnumber: 45,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'امير أحمد السيد أحمدمتولي',
      seatnumber: 46,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اياد احمد محمد طلبة',
      seatnumber: 47,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اياد أحمد السيد أحمدابراهيم',
      seatnumber: 48,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اياد محمد ابراهيم حسن',
      seatnumber: 49,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اياد وائل عادل رأفت رشاد',
      seatnumber: 50,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'بدرمحمد شعبان السعيد',
      seatnumber: 51,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'بلال محمود عبد المولى حامد عبد المولى',
      seatnumber: 52,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      profess_Skills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      tokkatsu: 'غ',
      result: 'غ',
    },
    {
      name: 'جلال إبراهيم علي مسعد علي الإمام',
      seatnumber: 53,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حبيب حازم محمد حسن أحمد العدوي',
      seatnumber: 54,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حسن احمد حسن محمد حسن الشاعر',
      seatnumber: 55,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حسين محمد حسين الدمرداش',
      seatnumber: 56,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حمادة كريم توكل أبو المعاطي',
      seatnumber: 57,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حمدي عماد حمدي محمد عبد الحميد',
      seatnumber: 58,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حمزة باسم مرعي علي طالب',
      seatnumber: 59,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رضا محمد رضا احمد محمود حيدر',
      seatnumber: 60,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريان وسيم محمد الهادي محمد',
      seatnumber: 61,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'زياد أحمد أمين عبده علي السيد',
      seatnumber: 62,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'زياد أحمد صالح عبد الرازق رزق',
      seatnumber: 63,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سيف السيد صبري منصور السعيد',
      seatnumber: 64,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سيف أحمد محمد سيف الدين حامد',
      seatnumber: 65,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سيف سامي عبده عبده السيد حسن العربي',
      seatnumber: 66,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سيف محمود مصطفى ابراهيم حسن',
      seatnumber: 67,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عادل كمال عادل كمال حسن',
      seatnumber: 68,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عبد الرحمن أحمد محمود محمد السيد',
      seatnumber: 69,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      profess_Skills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      tokkatsu: 'غ',
      result: 'غ',
    },
    {
      name: 'عبد الله محمد محمد ابراهيم',
      seatnumber: 70,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عبد الهادي محمد ابراهيم جاد',
      seatnumber: 71,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'علي إبراهيم محمد إبراهيم محمد',
      seatnumber: 72,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمار السيد المتولى كامل المتولى',
      seatnumber: 73,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمر إبراهيم إبراهيم حسن سليمان',
      seatnumber: 74,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمر إبراهيم رشدي نصر',
      seatnumber: 75,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمر محسن محمد حسن إسماعيل',
      seatnumber: 76,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمر وليد ميمي عبده إبراهيم',
      seatnumber: 77,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمرو خالد  أنور عبد الرحمن زهره',
      seatnumber: 78,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمرو فريد شوقي جمعه الوصيف',
      seatnumber: 79,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عمرو محمد عبد العظيم حامد محمد',
      seatnumber: 80,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'فادي عصام علي علي فرج',
      seatnumber: 81,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'فؤاد رجب فؤاد عوض أبو سالم',
      seatnumber: 82,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'كمال المتولي كمال محمود',
      seatnumber: 83,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'لؤي محمد رشدي محمد فرج',
      seatnumber: 84,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مازن إبراهيم مازن مسعد علي الإمام',
      seatnumber: 85,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مالك محمد السيد عبد العال صابر',
      seatnumber: 86,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد إسلام السيد صالح خالد',
      seatnumber: 87,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد أحمد أحمد حسنين محمد',
      seatnumber: 88,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد أحمد توكل أحمد أحمد عز الدين',
      seatnumber: 89,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد أحمد محمد السيد إبراهيم حامد',
      seatnumber: 90,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد أحمد محمد فؤاد محمد مراد',
      seatnumber: 91,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد حازم حسنين عبد الغني أحمد بدوي',
      seatnumber: 92,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد حازم فتحي الحنفي صلاح',
      seatnumber: 93,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد خالد محمد عبد الفتاح',
      seatnumber: 94,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد رضا عبد الرحمن السيد عبد الوهاب',
      seatnumber: 95,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد طارق محمود محمود علي سراج',
      seatnumber: 96,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد عادل إبراهيم محمد السيد',
      seatnumber: 97,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد محمود السيد أحمد علام',
      seatnumber: 98,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد مصطفى حامد الحداد',
      seatnumber: 99,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد نصر محمد عبد السلام',
      seatnumber: 100,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد وائل أحمد محمد محمد أحمد صلاح',
      seatnumber: 101,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمد وليد السيد عبد العظيم عبد الوهاب',
      seatnumber: 102,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمود السيد محمود محمد حسنين بدوي',
      seatnumber: 103,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمود حلمي محمود محمد حسنين',
      seatnumber: 104,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'محمود محمد عزت السيد محمد العياضي',
      seatnumber: 105,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مروان أحمد محمود أحمد محمد القلا',
      seatnumber: 106,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مصطفى محمد عزمي ابرااهيم حامد النشار',
      seatnumber: 107,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'معاذ سمير السيد العجمي المرسي',
      seatnumber: 108,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'معاذ محمد السيد عبد العال صابر',
      seatnumber: 109,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'نور محمد حسين عبد الفتاح ابراهيم',
      seatnumber: 110,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'هيثم عمرو نزيه نعمان محمد',
      seatnumber: 111,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'وائل محمد فؤاد عبد الشكورعبدالله',
      seatnumber: 112,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ياسين احمد محمد أحمد الصعيدي ',
      seatnumber: 113,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ياسين خالد السيدمحمد عبد الستار',
      seatnumber: 114,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ياسين محمد السيد عبدالمنعم السيد جبر',
      seatnumber: 115,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ياسين محمود أحمد عبدالفتاح محمد خليل',
      seatnumber: 116,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'يحي حازم فتحي الحنفي صلاح',
      seatnumber: 117,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'يس محمد على أحمد الوصيف',
      seatnumber: 118,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'يوسف خالد مطاوع إبراهيم مطاوع',
      seatnumber: 119,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'يوسف محمد السيد حامد المتولى',
      seatnumber: 120,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'يوسف محمد سعد عبد الوهاب',
      seatnumber: 121,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اروى أحمد محمد محمد نبيل',
      seatnumber: 122,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اروى محمود سعد السيد إبراهيم حماد',
      seatnumber: 123,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'اسيل محمود عبد الفتاح عبد الحميد المهندس',
      seatnumber: 124,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'امال السيد فهمي نصر المليجي',
      seatnumber: 125,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'امنيه محسن إبراهيم المرسي العياضي',
      seatnumber: 126,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'بسمله عبد الغني السيد السيد محمد مونس',
      seatnumber: 127,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'تقى السعيد محمود السعيد سليمان',
      seatnumber: 128,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'تولين حمدي السيد عبد الرؤف مصطفى',
      seatnumber: 129,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جنات السعيد المهدي عبد المنعم زياده',
      seatnumber: 130,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جنى السيد سليمان محمد عماشه',
      seatnumber: 131,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جنى أحمد السيد المتولي سليمان',
      seatnumber: 132,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جنى عمرو محمد عبد الحليم',
      seatnumber: 133,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جودي إبراهيم إبراهيم حسن حسين',
      seatnumber: 134,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جودي أحمد السعيد السعيد حسن ستيت',
      seatnumber: 135,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'جودي مأمون مأمون محمود محمد الباز',
      seatnumber: 136,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حبيبه محمود سيد أحمد متولي',
      seatnumber: 137,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حبيبه محمود محمد السعيد المتولي',
      seatnumber: 138,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حلا أحمد السيد إبراهيم العشري',
      seatnumber: 139,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حنين عبده محمد محمد أحمد',
      seatnumber: 140,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'حنين كريم فهيم السيد حسن',
      seatnumber: 141,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'دنيا محمد محمد السعيد محمد سالم',
      seatnumber: 142,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رقيه هيثم محمد أحمد جوهر عبد الخالق',
      seatnumber: 143,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رهف بدير عباس محمد الشحات',
      seatnumber: 144,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رهف تامر محمد طاهر ميرغني',
      seatnumber: 145,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رودينا أحمد أحمد عبد الحليم جمعه',
      seatnumber: 146,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رودينا محمد أحمد محمد حبش',
      seatnumber: 147,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'روضة وجيه إبراهيم عيد يوسف',
      seatnumber: 148,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريتاج عماد رشاد أبو المعاطي',
      seatnumber: 149,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريتال جابر شفيق السيد أحمد',
      seatnumber: 150,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريتال علي محمد فؤاد محمد',
      seatnumber: 151,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريماس إبراهيم عبد الشافي',
      seatnumber: 152,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريماس حسام محمد عبد الرحمن علي عبد العال',
      seatnumber: 153,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريماس حسني أيمن حسني توفيق',
      seatnumber: 154,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ريماس وليد جمعه محمد علي',
      seatnumber: 155,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'زينب محمد السيد السيد شبانه',
      seatnumber: 156,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'زينه إبراهيم أحمد عبد الحميد حسانين بدوي',
      seatnumber: 157,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'زينه أشرف محمد إبراهيم بدوي',
      seatnumber: 158,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سلمى عزيز عبد المنعم عبد الرازق المتولي',
      seatnumber: 159,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سلوى حاتم سمير محمود ابوالمعاطي',
      seatnumber: 160,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سما إبراهيم طاهر عبد العال صابر',
      seatnumber: 161,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سما أحمد إبراهيم عبد السلام أحمد',
      seatnumber: 162,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سما عباس رشاد محمود الحديدي',
      seatnumber: 163,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سما محمد حسنين علي علي محمد',
      seatnumber: 164,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'سمر تامر عوض محمد عيسى',
      seatnumber: 165,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'شروق محمد منصور محمد سليمان المراكبي',
      seatnumber: 166,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'شهد عبد العظيم أحمد سيد أحمد زهره',
      seatnumber: 167,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'شهد محمد أحمد المرسي ربيع',
      seatnumber: 168,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'عزه محمد مختار منصور محمد إبراهيم',
      seatnumber: 169,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'غرام محمد محمد محمود الباز',
      seatnumber: 170,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'فاطمه محمد محمد إبراهيم محمود الشابوري',
      seatnumber: 171,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'فيروز محمودأبو حلاوه أحمد محمود يس',
      seatnumber: 172,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'لميس أحمد محمد عبد المنعم حسن حسانين',
      seatnumber: 173,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'لوجين أحمد صبري عيد سيد أحمد',
      seatnumber: 174,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ليان تامر سمير السيد أحمد خيوه',
      seatnumber: 175,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'لين محمد السعيد محمد المنسي',
      seatnumber: 176,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مرام محمد ناصف إبراهيم المندراوي',
      seatnumber: 177,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مروه السيد محمود سلامه السيد',
      seatnumber: 178,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مريم أحمد عصام عبد المعطي النحاس',
      seatnumber: 179,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مريم رضا المتولي محمد علي',
      seatnumber: 180,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مريم علي إبراهيم المغازي إبراهيم',
      seatnumber: 181,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'مريم وائل محمد محمود المتولي النجار',
      seatnumber: 182,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ملك أنيس محمد عبد الفتاح',
      seatnumber: 183,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ملك عمرو إبراهيم المتولي الوصيف',
      seatnumber: 184,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ملك محمد إبراهيم مرسي العجمي',
      seatnumber: 185,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ملك وائل محمد عبدين بدوي',
      seatnumber: 186,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'منه السيد المهدي محمد حسنين',
      seatnumber: 187,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'منى السيد محمود سلامه السيد',
      seatnumber: 188,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'منى عبد الفتاح إبراهيم حسن سليمان',
      seatnumber: 189,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ميرال محمد إبراهيم محمود يوسف',
      seatnumber: 190,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'نورهان عبد العظيم محمد محمد عبد الستار',
      seatnumber: 191,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'نورين السيد محمد إبراهيم عبد العال ستيت',
      seatnumber: 192,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'هلا هاني جبر محمد المرسي',
      seatnumber: 193,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'هنا السيد محمد عبدالفتاح ابراهيم',
      seatnumber: 194,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'هنا هاني جبر محمد المرسي',
      seatnumber: 195,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'ولاء عماد الدين عبده محمد مصطفى',
      seatnumber: 196,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'رودينا محمد محمد الدسوقي ابراهيم',
      seatnumber: 197,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
    {
      name: 'فريد محمد الحسيني محمد ابو العنين',
      seatnumber: 198,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'اجتاز',
    },
  ];

  seatNumber: number | null = null;
  selectedStudent: Student | null = null;

  searchStudent() {
    this.selectedStudent =
      this.students.find((student) => student.seatnumber === this.seatNumber) ||
      null;
  }
}
