import { NgFor, NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Student {
  name: string;
  arabic: string;
  english: string;
  math: string;
  interdisciplinary: string;
  physical_education: string;
  religion: string;
  values: string;
  tokkatsu: string;
  result: string;
}

@Component({
  selector: 'app-first-grade',
  imports: [NgFor, NgIf, FormsModule],
  templateUrl: './first-grade.component.html',
  styleUrl: './first-grade.component.css',
})
export class FirstGradeComponent {
  students: Student[] = [
    {
      name: 'ابراهيم محمود ثروت إبراهيم العدل',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد اسلام أحمد عيد سيدأحمد صالح',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد أحمد فؤاد محمد مراد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد أسامه محمد عبدالسلام محمد زويته',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد تامر عادل محمود محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد حسن محمد إبراهيم عيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد حميدو عثمان إبراهيم الوصيف',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم  أنيس محمود عبد الفتاح السيد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم السيد السيد أحمد يسن ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم عماد رشاد ابو المعاطي  الموجي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر عماد حمدي محمد عبد المجيد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'السيد إبراهيم السيد إبراهيم السيد اسماعيل',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايمن أحمد عوض طه يوسف',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بدر ناجي توكل الششتاوي علي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تميم أحمد مكرم تمام عبدالجواد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسام إبراهيم محمد كمال إبراهيم رمضان',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسام هشام محمد المتولي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حمادة محمد حمادة عبدالفتاح أحمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حمزه حسام  الحديدي أحمد عبد المقصود',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حمزه سمير المرسي محمود علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خالد أحمد أيمن السعيد محمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خالد هاني محمد السيد محمود',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد عبد العظيم أحمد سيد أحمد زهرة',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زين أحمد محمد سيف الدين حامد الغريب',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سادن طارق محمد محمود على الغرابلي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سامي  محمد أسامه محمد طلعت محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سليم خالد محمد علي محمد زهرة',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'سمير حاتم سمير محمود أبو المعاطي ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف معوض معوض عبدالهادي حجازي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'صلاح محمد السعيد محمد السعيد علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبدالرحمن محمد إبراهيم محمد رمضان',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبدالله أحمد محمد عبدالمنعم حسن حسنين',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمار أشرف محمدمحمد أحمد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر أشرف محمد محمد احمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر طارق محمود محمد علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر عباس فرحات محمد السيد أحمد الامام',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر مجدي جمعه نعمان عبد العال  ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر محمد السعيد أحمد عبدالعال',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كريم وائل محمد الهادي محمد عبد الملك',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك سمير المرسي محمود علي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك علاء سمير محمد اسماعيل المهندس',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'اجتاز',
      religion: 'أقل من المتوقع',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'برنامج علاجى',
    },
    {
      name: 'مالك يسري إبراهيم فهمي عبداللطيف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مجدي السيد محمد عبد الفتاح العدوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد مجدي أبو الفوايد محمد حسن',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد محمد أنور محمد عبدالواحد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد محمود محمد أحمد عبدالعال',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود عصام أحمد محمد البرماوي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان أحمد السيدعبدالرحمن زهرة',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان محمود أحمد  عبدالفتاح محمد خليل',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مهاب أحمد عبد الجليل شبل عبدالمطلب',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نبيل نبيل أحمد محمد علي شلبي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'وليد نادر محمد السيد السيد',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين القطب محمد رمضان فرحات',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين عزيز عبد المنعم عبدالرازق المتولي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين علاء الدين محمد وهبه أحمد ',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'غ',
      religion: 'أقل من المتوقع',
      values: 'غ',
      tokkatsu: 'غ',
      result: 'برنامج علاجى',
    },
    {
      name: 'ياسين محمد ثروت إبراهيم العدل',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين هاني المرسي المرسي الحنبلي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين وائل على رشاد السيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يحي أحمد عصام كامل رشاد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يزن جمعه محمود رمضان فرحات',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يسن خالد إبراهيم سعد علي',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'اجتاز',
      religion: 'أقل من المتوقع',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'برنامج علاجى',
    },
    {
      name: 'يسن عادل عثمان عيد أحمد صحيفة',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يسين الدسوقي حسين عبد الفتاح',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف ابراهيم احمد ابراهيم خليل',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف احمد إبراهيم فتوح محمد عبده',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف أشرف محمد السعيد محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف أيمن محمد حسن علي',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف جلال  الشبراوي حسين صلاح',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف شريف أشرف إبراهيم عابدين بدوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف طارق محمود محمود علي سراج',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يونس أحمد إبراهيم فتوح محمد عبده',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احلام إبراهيم السيد إبراهيم السيد اسماعيل',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسيل محمد السعيد محمد السعيد علي الشناوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايلين محمد فتحي محمد علي مقبل',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بتول أحمد شعبان السعيدعلي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تقى أحمد عبدالرحمن فتحي مصطفى عبدالنبي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تولين أحمد فؤاد عبد الفتاح إبراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي حازم محمد إبراهيم عابدين',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي محمد محمد علي علي محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جوري مجدي جمعه نعمان عبدالعال',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جينا السيد سيد احمد عبد السلام إبراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حور أحمد أحمد محمد علي شلبي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حياه عمرو السعيد حافظ رزق عوض',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رحمه ربيع محمد عبد الهادي حسنين علي',
      arabic: 'أقل من المتوقع',
      english: 'أقل من المتوقع',
      math: 'أقل من المتوقع',
      interdisciplinary: 'أقل من المتوقع',
      physical_education: 'اجتاز',
      religion: 'أقل من المتوقع',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'برنامج علاجى',
    },
    {
      name: 'ريتال كريم إبراهيم محمود المرسي شهده',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتال محمد السيد محمد السيد قيشه',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريماس علي أكرم  علي محمدين',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما هشام توكل محمود السيد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سماح سامح عزمي محمد محمد',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلا عبد الرحمن عادل عبد الفتاح إبراهيم',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'شاديه محمد حسنين علي علي محمد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عفاف محمد حسني محمد عبد الجواد',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كارما اشرف محمد إبراهيم بدوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كارما أيمن السيد إبراهيم حافظ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كارما تامر محمد محمد علي غنيم ',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كارما عصام عبدالسلام محمد عسكر',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لانا أبو بكر جميل لطفي عبده الطنطاوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليليان كمال عادل كمال حسن ',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروه مصطفى ماهر عبده محمد مصطفى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم عصام احمد محمد البرماوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكة أحمد مازن محمد حسنين',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكه اسلام السيد صالح خالد زبيب',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكه عماد حمدي محمد صالح',
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مكه كامل أشرف محمد اسماعيل الحربي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مي أحمد السيد محمد مصطفى',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مي عصام أحمد محمد البرماوي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يلبى التوقعات',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور السيد عبد الفتاح عبد الشكور عبد الله',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورسين محمد عثمان مسعد إبراهيم النادي',
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      interdisciplinary: 'يلبى التوقعات أحياناً',
      physical_education: 'اجتاز',
      religion: 'يلبى التوقعات',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورين محمد عبد الغني عبدالسميع عبدالنبي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا إبراهيم رمضان  إبراهيم المرسي',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'وعد ايمن ثروت علي الشربيني',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يارا محمد محمد عبدالوهاب محمد الوصيف',
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      interdisciplinary: 'يفوق التوقعات دائماً',
      physical_education: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      values: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
  ];
  studentName: string = '';
  selectedStudent: Student | null = null;

  searchStudent() {
    const input = this.studentName.trim();
    const words = input.split(' ');

    if (words.length < 3) {
      // أقل من 3 أسماء => ما تعرضش نتيجة
      this.selectedStudent = null;
      alert('أدخل اسم الطالب ثلاثي');
      return;
    }

    const firstThreeWords = words.slice(0, 3).join(' ');

    this.selectedStudent =
      this.students.find((s) => s.name.startsWith(firstThreeWords)) || null;
  }
}
