import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Student {
  name: string;
  seatnumber: number;
  arabic: string;
  math: string;
  studies: string;
  sciences: string;
  english: string;
  ict: string;
  profess_Skills: string;
  total: string;
  religion: string;
  art: string;
  physicalEducation: string;
  musicEducation: string;
  tokkatsu: string;
  result: string;
}

@Component({
  selector: 'app-sixth-grade',
  imports: [NgIf, FormsModule],
  templateUrl: './sixth-grade.component.html',
  styleUrl: './sixth-grade.component.css',
})
export class SixthGradeComponent {
  students: Student[] = [
    {
      name: 'ابراهيم صهيب أحمد يوسف خضر',
      seatnumber: 40,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد السيد احمد فؤاد عبدالرحمن',
      seatnumber: 41,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات أحياناً',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد السيد السيد محمد مصطفى عبد النبي',
      seatnumber: 42,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد إبراهيم علي علي الرطيل',
      seatnumber: 43,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد أحمد عبد الفتاح عبد الحميد المهندس',
      seatnumber: 44,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد خالد عباس محمد الشربيني',
      seatnumber: 45,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد علي المرسي السيد محمد شهده',
      seatnumber: 46,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد كريم مجدي عثمان عبد الرحمن شلبي',
      seatnumber: 47,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد فوزي عبد العظيم إسماعيل',
      seatnumber: 48,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمود محمد عبد المنعم مسعد قنديل',
      seatnumber: 49,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد ياسر بدير حامد عيد عبد النبي',
      seatnumber: 50,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم احمد سمير أبو الفوايد محمد حسن',
      seatnumber: 51,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم احمد محمد احمد عبده العيسوى',
      seatnumber: 52,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات أحياناً',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم عمرو أحمد محمد السعيد',
      seatnumber: 53,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم نصر محمد عبد السلام محمد',
      seatnumber: 54,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادهم محمد عادل عبد الله إبراهيم',
      seatnumber: 55,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات أحياناً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادهم هاني السيد خليل إبراهيم',
      seatnumber: 56,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسامه أيمن محمد عبده السيد عز الدين',
      seatnumber: 57,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسلام السيد محمود محمد العيسوي',
      seatnumber: 58,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسلام محمد السيد محمد حسن حجازي',
      seatnumber: 59,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اشرف عوض محمود إبراهيم',
      seatnumber: 60,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'السيد إبراهيم إبراهيم محمد السيد',
      seatnumber: 61,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'امير أشرف سمير محمود أبو المعاطي',
      seatnumber: 62,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد عماد الدين عبد البديع محمد البدوى',
      seatnumber: 63,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد فتحي السيد فتحي عبد الملك',
      seatnumber: 64,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد محمد ابراهيم علي الوصيف',
      seatnumber: 65,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد محمد السيد محمد رزق',
      seatnumber: 66,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد ياسر حلمي محمد العشري',
      seatnumber: 67,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'باسم عمرو شوقي جمعه الوصيف',
      seatnumber: 68,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بدير محمد بدير سليمان أبو المعاطي',
      seatnumber: 69,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسام مجدي أبو الفوايد محمد حسن',
      seatnumber: 70,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تامر مجدي ابراهيم محمد السيد',
      seatnumber: 71,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جمعه أحمد فؤاد محمد مراد',
      seatnumber: 72,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسن وليد حسن الشحات السيد أبو العطا',
      seatnumber: 73,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خالد وليد ابراهيم محمد رمضان',
      seatnumber: 74,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رافت راجح محمد جمعه الشافعي',
      seatnumber: 75,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد سامح السيد السيد حسن صالح',
      seatnumber: 76,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد كريم رمضان أحمد علي',
      seatnumber: 77,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد وليد محمد السعيد حسن',
      seatnumber: 78,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سمير خالد سمير محمد المرسي مرعي',
      seatnumber: 79,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف الدين أحمد السيد أحمد قنديل',
      seatnumber: 80,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'صديق ايمن محمد حسن علي',
      seatnumber: 81,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن أحمد عبدالرحمن عبد الفتاح',
      seatnumber: 82,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن طارق ابو حلاوة علي السيد غنيم',
      seatnumber: 83,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن محمود صلاح محمد حسن ستيت',
      seatnumber: 84,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله سامح أحمد فؤاد عبد الرحمن زهره ',
      seatnumber: 85,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'علي مجدي شعبان السعيد علي الرفاعي',
      seatnumber: 86,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر السيد السيد البسطويسي فرج',
      seatnumber: 87,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر جابر رشاد جابر مصطفى',
      seatnumber: 88,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر عادل محمد صبري محمد المهدي',
      seatnumber: 89,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر علاء محمد السيد حجازي',
      seatnumber: 90,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر مازن عادل عبده',
      seatnumber: 91,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      profess_Skills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      tokkatsu: 'غ',
      result: 'غ',
    },
    {
      name: 'عمر محمد المليجي المليجي بحيلق',
      seatnumber: 92,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر محمود محمد عرفان مقبل',
      seatnumber: 93,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمرو عادل علي محمد علي العجمي',
      seatnumber: 94,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فوزي طارق فوزي محمد يوسف',
      seatnumber: 95,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كريم أحمد ماهر إبراهيم محمد',
      seatnumber: 96,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك محمد عزمي نعمان أحمد',
      seatnumber: 97,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك محمود السيد رشاد شمس الدين',
      seatnumber: 98,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك محمود ثروت السيد سعد',
      seatnumber: 99,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السيد الشبراوي حسين صلاح',
      seatnumber: 100,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد أحمد إبراهيم عبد الفتاح حلاوه',
      seatnumber: 101,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد أحمد طاهر إبراهيم محمود ',
      seatnumber: 102,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد حمدينو عبد المنعم حسن حنين الشاعر',
      seatnumber: 103,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد خالد محمد أحمد أحمد خيوه',
      seatnumber: 104,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد رفيق معوض إبراهيم إبراهيم حبيب',
      seatnumber: 105,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد عبد اللطيف أحمد عبداللطيف أحمد ',
      seatnumber: 106,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد علاء البليسي عوض سليمان',
      seatnumber: 107,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد عمرو علي محمود الوصيف',
      seatnumber: 108,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد محمد القناوي حسن غانم ',
      seatnumber: 109,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد محمد ناجح سعد إبراهيم سعد',
      seatnumber: 110,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد هاني أبو الحسن علي البيومي',
      seatnumber: 111,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود ربيع محمود علي أحمد',
      seatnumber: 112,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود رضا محمد صبره إبراهيم',
      seatnumber: 113,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان عبد العزيز جمعه عبد العزيز',
      seatnumber: 114,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان محمد عماد الدين محمود محمد سعد',
      seatnumber: 115,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مصطفى ابراهيم محمد حافظ علي السيد الامام',
      seatnumber: 116,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'معاذ محمد السعودي ماهر الحنفي',
      seatnumber: 117,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مهند هاني محمد علي عز الدين',
      seatnumber: 118,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نديم محمد نديم محمد مصطفى عبد النبي',
      seatnumber: 119,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور نبيل محمد السيد السيد صلاح',
      seatnumber: 120,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هاني السيد السيد علي المعلواني',
      seatnumber: 121,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'وائل خالد عبد الحميد محمد أبو العينين',
      seatnumber: 122,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'وليد محمد معوض إبراهيم محمود العدوي',
      seatnumber: 123,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين طارق علي محمد علي العجمي ',
      seatnumber: 124,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف السعيد محمود السعيد محمد ',
      seatnumber: 125,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف صالح عبد الحميد محمد أبو العينين',
      seatnumber: 126,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف عادل محمد صبري محمد المهدي',
      seatnumber: 127,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف محمد محمد إبراهيم محمد الشابوري',
      seatnumber: 128,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف محمد محمد عبد الوهاب محمد الوصيف',
      seatnumber: 129,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ابرار محمود محمد ابراهيمم حمد شهاب الدين',
      seatnumber: 130,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احسان السيد جمعه السعيد محمود العشري',
      seatnumber: 131,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الاء ابراهيم السيد رمضان',
      seatnumber: 132,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الاء محمد معوض ابراهيم جمعه المتولي',
      seatnumber: 133,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الين اسامة صبري محمد محمد علي',
      seatnumber: 134,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'امل علي يوسف علي يوسف',
      seatnumber: 135,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايتن احمد محمود محمد يوسف',
      seatnumber: 136,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايمان اسلام ابراهيم ابراهيم حسنين ',
      seatnumber: 137,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايمان محمدالعجمي المتولي عمر البرماوي',
      seatnumber: 138,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بروين محمد أحمد السيد الغريب',
      seatnumber: 139,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسمله محمد مصطفى كامل متولي',
      seatnumber: 140,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسمله هاني محمد محمد المتولي',
      seatnumber: 141,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسمه محمد محمود الدسوقي زيدان',
      seatnumber: 142,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسنت ابراهيم محمود طه محمود',
      seatnumber: 143,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بيسان أحمد مصطفى النحاس  محمود الرفاعي',
      seatnumber: 144,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تولين السيد يوسف يسري عبد القادر',
      seatnumber: 145,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى أمجد حلمي حامد ابراهيم زياده',
      seatnumber: 146,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى كريم عزمي أحمد محمد',
      seatnumber: 147,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى محمد عرفات محمود محمد حبش',
      seatnumber: 148,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي السيد سيد احمد عبد السلام ابراهيم',
      seatnumber: 149,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي محمد المرسي عبد الفتاح المرسي العشري',
      seatnumber: 150,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي محمد ثروت عبدالعال',
      seatnumber: 151,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي محمد علي علي علي',
      seatnumber: 152,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جومانا السيد السيد محمد مصطفى عبد النبي',
      seatnumber: 153,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حبيبة السيد محمود محمد الديب',
      seatnumber: 154,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'دعاء علاء السيد أحمد أحمد الرطيل',
      seatnumber: 155,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رودينا حامد محمد هلال نعمان',
      seatnumber: 156,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'روضه رضا فتحي الحنفي صلاح',
      seatnumber: 157,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتاج تامر عبد القادر عبد الجليل عبد القادر',
      seatnumber: 158,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتال عمرو مجدي أسعد طه الباز',
      seatnumber: 159,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريفان ايمن محمود عبد الهادي أحمد',
      seatnumber: 160,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريماس وليد طه محمد طه محمد',
      seatnumber: 161,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريناد تامر عبد القادر عبد الجليل عبد القادر',
      seatnumber: 162,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سامية محمد محمد مقبل',
      seatnumber: 163,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي نادر محمد السيد السيد',
      seatnumber: 164,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سجى سامي طاهر محمدالبيومي سراج',
      seatnumber: 165,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سلمى ابراهيم عبد المنعم السيد حشيش',
      seatnumber: 166,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما بليغ منصور محمود عبد الجواد',
      seatnumber: 167,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سوسو وائل محمد جمعه الوصيف',
      seatnumber: 168,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'شهد رضا عثمان عبد العال عجيزه',
      seatnumber: 169,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فاطمة الزهراء السيد توكل محمود السيد',
      seatnumber: 170,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فاطمة أحمد الشبراوي عبد الرحمن علي',
      seatnumber: 171,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لجين محمود أحمد محمود محمد قنديل',
      seatnumber: 172,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لفين أكرم خاطر مختار محمد سرايا',
      seatnumber: 173,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لين نبيل محمد محمد سليمان الجعلى',
      seatnumber: 174,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليندا خالد سمير محمد المرسي مرعي',
      seatnumber: 175,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مدونا عادل عثمان عيد أحمد صحيفة ',
      seatnumber: 176,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات أحياناً',
      total: 'اجتاز',
      religion: 'يلبى التوقعات',
      art: 'يلبى التوقعات أحياناً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم ابراهيم محمد عبد العزيز ابراهيم',
      seatnumber: 177,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد حمدي محمد المهندس',
      seatnumber: 178,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد عبد العليم محمد عبد الستار',
      seatnumber: 179,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد عبداله عبدالله محمود حمدان',
      seatnumber: 180,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك محمد السيد السيد طه الباز',
      seatnumber: 181,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك محمد الوصيف جمعه الوصيف قيشه',
      seatnumber: 182,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'منال أحمد عوض طه يوسف',
      seatnumber: 183,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'منة الله محمد عماد الدين محمود محمد سعد',
      seatnumber: 184,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميار شريف سمير محمود عبد المجيد',
      seatnumber: 185,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميرا السيد صبري المتولي المتولي سماحه',
      seatnumber: 186,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميرنا أحمد حسن محمدحسن الشاعر',
      seatnumber: 187,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ندى المرسي عباس محمد السيد',
      seatnumber: 188,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور اسلام محمود عبد الرازق محمود العشري',
      seatnumber: 189,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نوران سيف اسماعيل نافع علي سالم ',
      seatnumber: 190,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورهان سيف اسماعيل نافع علي سالم ',
      seatnumber: 191,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورين خالد محمد مصطفى مصطفى',
      seatnumber: 192,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'همس وائل محمد الهادي محمد ',
      seatnumber: 193,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا الدسوقي حسين عبد الفتاح ابراهيم',
      seatnumber: 194,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا السيد سري محمود متولي عمر',
      seatnumber: 195,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا ايمن عبد الوهاب محمد عبد الوهاب',
      seatnumber: 196,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا طارق محمود محمد علي',
      seatnumber: 197,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا عبد العزيز المتولي عبد العزيز المتولي',
      seatnumber: 198,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      profess_Skills: 'يلبى التوقعات',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يلبى التوقعات',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا محمد السيد سليمان احمد صلاح',
      seatnumber: 199,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا محمد السيد عبد الرحمن زهره',
      seatnumber: 200,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      profess_Skills: 'يفوق التوقعات دائماً',
      total: 'اجتاز',
      religion: 'يفوق التوقعات دائماً',
      art: 'يفوق التوقعات دائماً',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
  ];

  seatNumber: number | null = null;
  selectedStudent: Student | null = null;

  searchStudent() {
    this.selectedStudent =
      this.students.find((student) => student.seatnumber === this.seatNumber) ||
      null;
  }
}
