students: Student[] = [
    {
      name: 'ابراهيم مجدي إبراهيم محمد منصور',
      seatnumber: 20,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد السعيد رفعت عبدالخبير جاد',
      seatnumber: 21,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد السيد معوض البيومي',
      seatnumber: 22,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد ابراهيم نعمان أحمد الوصيف',
      seatnumber: 23,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد احمد السيد عبد الرحمن زهره',
      seatnumber: 24,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد حسين مصطفى كامل متولي',
      seatnumber: 25,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد رجب فؤاد عوض',
      seatnumber: 26,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد صهيب أحمد يوسف خضر',
      seatnumber: 27,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد علاء الدين محمد وهبه أحمد',
      seatnumber: 28,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد علي محمد علي محمد على',
      seatnumber: 29,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      professionalSkills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'احمد عمرو إبراهيم سعد علي',
      seatnumber: 30,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد عصام النحاس',
      seatnumber: 31,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد نبيل أحمد محمد شلبي',
      seatnumber: 32,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد وليد أحمد محمد محمود المحجوب',
      seatnumber: 33,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد وليد حلمي أحمد',
      seatnumber: 34,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم السيد عادل عبد المنعم محمد',
      seatnumber: 35,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم جمعه السيد المتولي عبد الله',
      seatnumber: 36,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم طارق صبري عبده السيد',
      seatnumber: 37,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم محمد ثروت إبراهيم العدل',
      seatnumber: 38,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم محمد محسن محمود العشري',
      seatnumber: 39,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم محمد محمد خليل أحمد سليمان',
      seatnumber: 40,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادهم رضا محمد إبراهيم عابدين',
      seatnumber: 41,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر مصطفى كمال مصطفى',
      seatnumber: 42,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسلام إيهاب إبراهيم إبراهيم حسنين',
      seatnumber: 43,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسلام علاء الشبراوي عبد العال معوض',
      seatnumber: 44,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسلام محمد العجمي البرماوي',
      seatnumber: 45,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'امير منصور رمضان منصور',
      seatnumber: 46,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد إبراهيم مصطفى إبراهيم',
      seatnumber: 47,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد رامي صبري عيد سيد',
      seatnumber: 48,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايان بكر علي محمد نجم',
      seatnumber: 49,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تيم محمد أحمد مصطفى عبد العال',
      seatnumber: 50,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسام هاني معوض جمعه',
      seatnumber: 51,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسن صلاح غانم حسن غانم',
      seatnumber: 52,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رائد أمجد حمدي طه فرج',
      seatnumber: 53,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رائف طارق محمد محمود الغرابلي',
      seatnumber: 54,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان صلاح كمال غانم',
      seatnumber: 55,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زين مصطفى السيد الشحات',
      seatnumber: 56,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سامي محمد السيد السعيد العشري',
      seatnumber: 57,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      professionalSkills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'سعد محمد سعد عبد الله',
      seatnumber: 58,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف أحمد إبراهيم عبد الفتاح حلاوه',
      seatnumber: 59,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف أيمن السيد العدل أبو الروس',
      seatnumber: 60,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف عبد الفتاح عادل عبد الفتاح إسماعيل',
      seatnumber: 61,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'طارق مجدي محمد عبد الرحمن عبد الغني',
      seatnumber: 62,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن انور محمد محمد الشربيني احمد',
      seatnumber: 63,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن أسامه محمد عبد السلام زويته',
      seatnumber: 64,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن محمد عبد الصابر الدسوقي',
      seatnumber: 65,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله محمد إبراهيم محمد رمضان',
      seatnumber: 66,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله محمود عبد الله عبد الله حمدان',
      seatnumber: 67,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبدالله يوسف محمد أحمد سيف الله',
      seatnumber: 68,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عزت جابر رشاد جابر',
      seatnumber: 69,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'علي عبد العظيم صالح أحمد أبو الحمايل',
      seatnumber: 70,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'علي محمد هاشم عبد الحميد هاشم',
      seatnumber: 71,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عماد الدين نصر عماد الدين عبد العزيز',
      seatnumber: 72,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر علي محمد علي محمد',
      seatnumber: 73,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فادي فتحي السيد فتحي عبد الملك',
      seatnumber: 74,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كريم السيد محمد العجمي مغربيه',
      seatnumber: 75,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك إبراهيم محمد عبد العزيز',
      seatnumber: 76,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك أحمد المرسي محمد المرسي العشري',
      seatnumber: 77,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك عماد رضا بدوي',
      seatnumber: 78,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك عمرو جلال عبد المجيد سليمان',
      seatnumber: 79,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السيد شوقي محمود العشري',
      seatnumber: 80,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد إبراهيم عواد يوسف',
      seatnumber: 81,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد أحمد جمعه بكر النجار',
      seatnumber: 82,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد أيمن محمد إبراهيم عابدين',
      seatnumber: 83,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد خالد المرسي إبراهيم هدهد',
      seatnumber: 84,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد رماح السيد عبد الحميد',
      seatnumber: 85,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد محمد علي طاهر علي',
      seatnumber: 86,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً ',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد هشام محمد المتولي عبد الوهاب',
      seatnumber: 87,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً ',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد وائل رمضان منصور',
      seatnumber: 88,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود عثمان السعيد أبو المعاطي',
      seatnumber: 89,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود محمد السيد عبد العال',
      seatnumber: 90,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'معاذ هيثم السيد الصياد',
      seatnumber: 91,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'معتز ياسر محمود محمد عجيز',
      seatnumber: 92,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مؤيد الحسين السيد الدمرداش',
      seatnumber: 93,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نبيل نبيل محمد محمد',
      seatnumber: 94,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين أحمد محمد إبراهيم رزق سالم',
      seatnumber: 95,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين محمد عبد الحميد أبو العينين',
      seatnumber: 96,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يحيي حماده محمد إبراهيم عباس',
      seatnumber: 97,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات أحياناً',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف السيد عبد الفتاح عبد الشكور',
      seatnumber: 98,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف السيد محمد الخميسي أحمد',
      seatnumber: 99,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف خير السيد حسن أمين الديب',
      seatnumber: 100,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف هاني محمود إبراهيم',
      seatnumber: 101,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ابرار حمدى السيد سالم منتصر',
      seatnumber: 102,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اروى كريم مجدي شلبي',
      seatnumber: 103,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اشرقت طارق السيد بديرحماد',
      seatnumber: 104,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الين أبو العز أبو ضيف محمد حسن',
      seatnumber: 105,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الين حسين مصطفى كامل متولي',
      seatnumber: 106,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الين رامي صبري عيد سيد',
      seatnumber: 107,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اميرة اشرف ابراهيم عبد السلام',
      seatnumber: 108,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اميره أحمد عصام كامل رشاد',
      seatnumber: 109,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اميره رضا محمد إبراهيم عابدين',
      seatnumber: 110,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايسل بسام ممدوح محمود عبدالرؤوف',
      seatnumber: 111,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايلين أحمد عمر أبو ضيف محمد',
      seatnumber: 112,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بسمله السيد توكل محمود',
      seatnumber: 113,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تلا محمود أحمد محمود قنديل',
      seatnumber: 114,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنا كامل إبراهيم إبراهيم',
      seatnumber: 115,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنة علي أحمد البظ',
      seatnumber: 116,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً ',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنة محمد عيسى علي محمد',
      seatnumber: 117,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى أيمن صبحي محمد المهدي',
      seatnumber: 118,
      arabic: 'يلبى التوقعات',
      math: '',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى محمد أحمد محمد بديع',
      seatnumber: 119,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي السيد السيد أحمد حسنين',
      seatnumber: 120,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي خالد عبد الحميد أبوالعنين',
      seatnumber: 121,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جوري أحمد السيد عبد الجليل',
      seatnumber: 122,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جوري أحمد عبدالوهاب محمد',
      seatnumber: 123,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جومانا خالد محمد أحمد خيوة',
      seatnumber: 124,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جومانه محمد السيد أحمد الديب',
      seatnumber: 125,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حراء رضا السيد عبد العال',
      seatnumber: 126,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'دارين خالد السيد هدهد',
      seatnumber: 127,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رغد محمد عبد الفتاح محمد إبراهيم',
      seatnumber: 128,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رهف أحمدعبد المنعم محمد صلاح',
      seatnumber: 129,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رودي السعيد محمود السعيد',
      seatnumber: 130,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رودينا أحمد محمود إبراهيم عوض',
      seatnumber: 131,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'روفان حلمي حلمي محمد العشري',
      seatnumber: 132,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رؤى محمد عبد السميع عبد الفتاح العدوي',
      seatnumber: 133,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتاج إبراهيم مازن مسعد الامام',
      seatnumber: 134,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً ',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتال محمود عبد المولى حامد عبد المولى',
      seatnumber: 135,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      professionalSkills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'ريماس إبراهيم السيد إبراهيم أحمد',
      seatnumber: 136,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريماس محمد عبد المولى على محمود',
      seatnumber: 137,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زينب جمعه جمعه حافظ رزق',
      seatnumber: 138,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي السيد جمعه محمد',
      seatnumber: 139,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي السيد مجاهد عبد المجيد الكناني',
      seatnumber: 140,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي أحمد محمد الوصيف جمعه',
      seatnumber: 141,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي محمد السيد محمد رزق',
      seatnumber: 142,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات أحياناً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سلمى علي يوسف علي يوسف',
      seatnumber: 143,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما أحمد حمدي رأفت رشاد',
      seatnumber: 144,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلفا خالد سمير محمد المرسي مرعي',
      seatnumber: 145,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'شمس مازن عادل عبده',
      seatnumber: 146,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      professionalSkills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'كارما محمد السيد المتولي عبد المعطي',
      seatnumber: 147,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لانا خالد محمد علي زهره',
      seatnumber: 148,
      arabic: 'غ',
      math: 'غ',
      studies: 'غ',
      sciences: 'غ',
      english: 'غ',
      ict: 'غ',
      professionalSkills: 'غ',
      total: 'غ',
      religion: 'غ',
      art: 'غ',
      physicalEducation: 'غ',
      musicEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'لوجين عصام عبد السلام محمد عسكر',
      seatnumber: 149,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لوجينا فاروق محمد إبراهيم نصر',
      seatnumber: 150,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليان اسلام ابراهيم احمد الديب',
      seatnumber: 151,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليان عماد حمدي محمد',
      seatnumber: 152,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليزاخالد سمير محمد المرسي مرعي',
      seatnumber: 153,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليليان السيد محمد محمد السعيد يعقوب',
      seatnumber: 154,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ماسه محمد محمد مسعد',
      seatnumber: 155,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مايا السيد صبري المتولي المتولي',
      seatnumber: 156,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد أحمد نعمان',
      seatnumber: 157,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك إبراهيم إبراهيم السيد',
      seatnumber: 158,
      arabic: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك إبراهيم نعمان أحمد',
      seatnumber: 159,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك إسلام أحمد عيد سيد صالح',
      seatnumber: 160,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك أحمد عوض طه يوسف',
      seatnumber: 161,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك أشرف محمد السعيد',
      seatnumber: 162,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مليكه محمد محمد المتولي النجار',
      seatnumber: 163,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مليكه ناجي الششتاوي علي',
      seatnumber: 164,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميار أحمد أحمد حسانين الغنام',
      seatnumber: 165,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات أحياناً',
      sciences: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميسم محمد ناصف إبراهيم',
      seatnumber: 166,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نادين نبيل أحمد محمد علي شلبي',
      seatnumber: 167,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ناديه خالد سمير السيد إبراهيم',
      seatnumber: 168,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نسمه نادر ممدوح حسن علي',
      seatnumber: 169,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نها أشرف ممدوح عبد الله إبراهيم حبيب',
      seatnumber: 170,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور محمود محمد محمد مسعد رضوان',
      seatnumber: 171,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورسين طارق محمود محمد علي',
      seatnumber: 172,
      arabic: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      studies: 'يلبى التوقعات',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نورلين رامي نور الدين عبد الباسط',
      seatnumber: 173,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماًيلبى التوقعات',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      ict: '',
      professionalSkills: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هاجر عبد الرحمن عادل عبد الفتاح',
      seatnumber: 174,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هايدي محمد حمدي محمد عبد الحميد',
      seatnumber: 175,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هاندا وائل عبد العليم غنيم',
      seatnumber: 176,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا السيد السيد البسطويسي',
      seatnumber: 177,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يلبى التوقعات',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا إبراهيم أحمد عبد المنعم',
      seatnumber: 178,
      arabic: 'يلبى التوقعات',
      math: 'يلبى التوقعات أحياناً',
      studies: 'يلبى التوقعات',
      sciences: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هنا محمد أحمد محمد الديب',
      seatnumber: 179,
      arabic: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      studies: 'يفوق التوقعات دائماً',
      sciences: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      ict: 'يفوق التوقعات دائماً',
      professionalSkills: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      art: 'اجتياز',
      physicalEducation: 'اجتاز',
      musicEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
  ];