import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Student {
  name: string;
  seatnumber: number;
  arabic: string;
  english: string;
  math: string;
  multidisciplinary: string;
  total: string;
  religion: string;
  physicalAndHealthEducation: string;
  valuesAndRespectForOthers: string;
  tokkatsu: string;
  result: string;
}

@Component({
  selector: 'app-third-grade',
  imports: [NgIf, FormsModule],
  templateUrl: './third-grade.component.html',
  styleUrl: './third-grade.component.css',
})
export class ThirdGradeComponent {
  students: Student[] = [
    {
      name: 'ابراهيم معوض عبده المرسي العشري',
      seatnumber: 10,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد ابراهيم علي ابراهيم محمد',
      seatnumber: 11,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد حسنى أيمن حسنى توفيق',
      seatnumber: 12,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد احمد محمد احمد',
      seatnumber: 13,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'احمد محمد صالح عبد الحميد',
      seatnumber: 14,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم احمد عبد الجليل شبل',
      seatnumber: 15,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم السعيد محمود السعيد الشافعي',
      seatnumber: 16,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم حسن فاروق محمد ابو العطا',
      seatnumber: 17,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات أحياناً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادم  محمد حسين الدمرداش',
      seatnumber: 18,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ادهم حسين محمد محمود احمد الضو',
      seatnumber: 19,
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر اسلام محمد محمد احمد عطيه ربيع',
      seatnumber: 20,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر السيد عزمي عبدالفتاح',
      seatnumber: 21,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسر عبدالله محمد ابراهيم شهاب الدين',
      seatnumber: 22,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اياد هاني السيد خليل ابراهيم',
      seatnumber: 23,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ايمن احمد عبد الوهاب محمد',
      seatnumber: 24,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'براء صلاح كمال غانم حسن غانم',
      seatnumber: 25,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تيم الله مازن عادل عبده',
      seatnumber: 26,
      arabic: 'غ',
      english: 'غ',
      math: 'غ',
      multidisciplinary: 'غ',
      total: 'غ',
      religion: 'غ',
      physicalAndHealthEducation: 'غ',
      valuesAndRespectForOthers: 'غ',
      tokkatsu: 'غ',
      result: 'دور تاني',
    },
    {
      name: 'حسن محمد حسن عبدالله ابراهيم حبيب',
      seatnumber: 27,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حسين ميثاق عباس صحيب',
      seatnumber: 28,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان محمد إبراهيم حسن حسين',
      seatnumber: 29,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريان وليد محمد طه',
      seatnumber: 30,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد طارق عزمي إبراهيم حامد النشار',
      seatnumber: 31,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زياد محمد محمد إبراهيم محمد الشابوري',
      seatnumber: 32,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'زين علاء سمير محمد المهندس',
      seatnumber: 33,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سادن إياد حسني صالح توفيق العدل',
      seatnumber: 34,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساهر محمد الوصيف جمعه قيشه',
      seatnumber: 35,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيف محمد شوقى المتولى',
      seatnumber: 36,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن على ثروت على الشربينى',
      seatnumber: 37,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن علي محمد فؤاد محمد',
      seatnumber: 38,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الرحمن محمد السعيد احمد عبد العال',
      seatnumber: 39,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله السيد السيد إبراهيم أحمد العجمي',
      seatnumber: 40,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله سمير المرسي محمود علي',
      seatnumber: 41,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله شريف محمد محمد عبد الهادي',
      seatnumber: 42,
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عبد الله يحيي عبد الله محمد العفيفى',
      seatnumber: 43,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عدي رضا توفيق توفيق السيد شلبايه',
      seatnumber: 44,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'علي محمد أحمد محمد حجازي',
      seatnumber: 45,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر أحمد طه السيد عبد الرحمن كيوان',
      seatnumber: 46,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر علاء عبد الغني أحمد بدوي',
      seatnumber: 47,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'عمر علاء محمود أبوهاشم معروف',
      seatnumber: 48,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'قدري محمد محمد السعيد أحمد',
      seatnumber: 49,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك محمد انور العدوي الباز',
      seatnumber: 50,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مالك محمد ثروت  عبد العال',
      seatnumber: 51,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السعيد محمد السعيد السيد',
      seatnumber: 52,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد السيد محمود محمد حسانين',
      seatnumber: 53,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد أحمد عبد اللطيف أحمد الوصيف',
      seatnumber: 54,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد حسام الدين علي السعيد علي',
      seatnumber: 55,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد خالد محمد مصطفى مصطفى',
      seatnumber: 56,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد سميح محمد السيد محمود',
      seatnumber: 57,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد عزت طلعت مصطفى صابر',
      seatnumber: 58,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد عمرو محمد عبد الحميد',
      seatnumber: 59,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمد هيثم محمد أحمد جوهر عبد الخالق',
      seatnumber: 60,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود محمد السعيدعلي علي',
      seatnumber: 61,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'محمود محمد محمود الدسوقي زيدان',
      seatnumber: 62,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مروان محمد عزمي نعمان أحمد',
      seatnumber: 63,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'معاذ محمد عبد العظيم حامد محمد',
      seatnumber: 64,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور عبد الوهاب إبراهيم عبد الوهاب الغندور',
      seatnumber: 65,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين إبراهيم إبراهيم حسن',
      seatnumber: 66,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين محمد العجمي المتولي',
      seatnumber: 67,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسين محمد عبد الحليم السيد حسين',
      seatnumber: 68,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يحيي محمد محمد السيد إبراهيم الشهاوي',
      seatnumber: 69,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يزن السيد سمير رمضان أمين',
      seatnumber: 70,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يس أحمد سمير أبو الفوايد محمد',
      seatnumber: 71,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يس عبد العزيز جمعه عبد العزيز',
      seatnumber: 72,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'يوسف ياسر المرسي سيد أحمد شرشيره',
      seatnumber: 73,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ابرار محمود سعد السيد إبراهيم حماد',
      seatnumber: 74,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اروى محمود سعيد محروس السيد',
      seatnumber: 75,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اسيل أيمن أحمد علي شلبايه',
      seatnumber: 76,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'الين ياسر حلمي محمد العشري',
      seatnumber: 77,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'اميرة عبد السلام محمد السيد',
      seatnumber: 78,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'بشرى ناجح فؤاد محمد إبراهيم',
      seatnumber: 79,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تاليا أحمد حافظ طاهر علي',
      seatnumber: 80,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'تولين محمد أمين المهدي محمد علوش',
      seatnumber: 81,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنا السيد أحمد فؤاد عبد الرحمن',
      seatnumber: 82,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يلبى التوقعات',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جنى محمد حلمي عبد الحميد بلال',
      seatnumber: 83,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جودي إبراهيم عبدالعال عبد الرحمن عبد العال',
      seatnumber: 84,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جومانا عماد حمدي عبد السلام',
      seatnumber: 85,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'جويريه عمرو مجدي أسعد طه الباز',
      seatnumber: 86,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حبيبه محمد محمود مصطفى سالم',
      seatnumber: 87,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'حبيبه وائل إبراهيم فهمي',
      seatnumber: 88,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'خلود السعيد العدل العدل محمد',
      seatnumber: 89,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'دعاء محمد أحمد محمد أحمد',
      seatnumber: 90,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'دنيا عماد بدوي عبد الرحمن',
      seatnumber: 91,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'راما طارق محمد عبد الرازق',
      seatnumber: 92,
      arabic: 'يلبى التوقعات',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رغد هاني صبري شحاته عبده',
      seatnumber: 93,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رقية وليد عبده عبدالعال صابر',
      seatnumber: 94,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رنوة محمود أبو حلاوه أحمد يس',
      seatnumber: 95,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'رودينا هاني عادل إبراهيم عباس',
      seatnumber: 96,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتاج إيهاب السيد إبراهيم',
      seatnumber: 97,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ريتاج حماده السيد إبراهيم',
      seatnumber: 98,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ساندي أشرف عبد الخالق محمد',
      seatnumber: 99,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سلمى السيد المندوه محمد',
      seatnumber: 100,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سلمى إبراهيم محمود طه',
      seatnumber: 101,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما سمير فوزي محمد',
      seatnumber: 102,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سما محمد الشربيني السيد محمد',
      seatnumber: 103,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلا السيد سمير رمضان أمين',
      seatnumber: 104,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلا رامي محمد محمود مونس',
      seatnumber: 105,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلا محمد حسن عبدالله إبراهيم حبيب',
      seatnumber: 106,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'سيلين عزيز عبد المنعم عبدالرزاق المتولي',
      seatnumber: 107,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'شيرين وليد مصطفى كامل',
      seatnumber: 108,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فاطمة السيد إبراهيم منصور',
      seatnumber: 109,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فريده عماد حسن السيد إبراهيم',
      seatnumber: 110,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'فيروز أحمد عبد الرحمن مصطفى',
      seatnumber: 111,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'كاندي محمد عرفات محمود حبش',
      seatnumber: 112,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لبنى أيمن محمد إبراهيم عابدين',
      seatnumber: 113,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لوجين محمد مسعد السعيد أبو المعاطى',
      seatnumber: 114,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ليليان أسامه صبري محمد',
      seatnumber: 115,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لين رامي محمد السعيد',
      seatnumber: 116,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'لين عمرو محمد إبراهيم',
      seatnumber: 117,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ماجدة محمد محمد محمود',
      seatnumber: 118,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ماريا حسين مصطفى كامل',
      seatnumber: 119,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد عزت السيد العياضي',
      seatnumber: 120,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مريم محمد محمد عبد السلام محمد متولي',
      seatnumber: 121,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك السيد محمد محمود حسين',
      seatnumber: 122,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ملك سمير عبد الفتاح سعد إبراهيم',
      seatnumber: 123,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مليكه إسلام السيد صالح خالد',
      seatnumber: 124,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'مي أحمد عبد العزيز عطوه',
      seatnumber: 125,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ميرال محمود محمد أحمد عبد العال',
      seatnumber: 126,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور عبد العظيم صالح محمد',
      seatnumber: 127,
      arabic: 'يلبى التوقعات',
      english: 'يلبى التوقعات',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'نور محمد جاد حسانين جاد',
      seatnumber: 128,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هاندا جمال حسين عبد الله',
      seatnumber: 129,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هدير عبد الهادي محمد إسماعيل خضر',
      seatnumber: 130,
      arabic: 'يلبى التوقعات أحياناً',
      english: 'يلبى التوقعات أحياناً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يلبى التوقعات أحياناً',
      religion: 'يلبى التوقعات أحياناً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هلا وائل محمد الهادي محمد',
      seatnumber: 131,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'هميس محمد حافظ طاهر',
      seatnumber: 132,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يلبى التوقعات',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
    {
      name: 'ياسمين صبري عبد المنعم محمود',
      seatnumber: 133,
      arabic: 'يفوق التوقعات دائماً',
      english: 'يفوق التوقعات دائماً',
      math: 'يفوق التوقعات دائماً',
      multidisciplinary: 'يفوق التوقعات دائماً',
      total: 'يفوق التوقعات دائماً',
      religion: 'يفوق التوقعات دائماً',
      physicalAndHealthEducation: 'اجتاز',
      valuesAndRespectForOthers: 'اجتاز',
      tokkatsu: 'اجتاز',
      result: 'ناجح',
    },
  ];

  seatNumber: number | null = null;
  selectedStudent: Student | null = null;

  searchStudent() {
    this.selectedStudent =
      this.students.find((student) => student.seatnumber === this.seatNumber) ||
      null;
  }
}
